### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by liranfarage89**

### CODE REVIEW

**Comment by liranfarage89** [comment]
env0 foo

**Comment by liranfarage89** [comment]
env0 foo

**Comment by liranfarage89** [comment]
env0 help

**Comment by liranfarage89** [comment]
env0 help

**Comment by liranfarage89** [comment]
env0 help

**Comment by liranfarage89** [comment]
env0 help

**Comment by liranfarage89** [comment]
env0 help

**Comment by liranfarage89** [comment]
env0 help

**Comment by liranfarage89** [comment]
env0 help

**Comment by liranfarage89** [comment]
env0 help

**Comment by alonnoga** [comment]
env0 help

**Comment by liranfarage89** [comment]
env0 help

**Comment by liranfarage89** [comment]
sdfs

**Pull request merged**
